# https://hydra.cc/docs/configure_hydra/intro/

## enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

job:
  env_copy:
    - PROJECT_ROOT

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${task_name}/runs/${now:%Y_%m_%d}/${now:%H_%M_%S}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${now:%Y_%m_%d}/${now:%H_%M_%S}
  subdir: ${hydra.job.num}

job_logging:
  formatters:
    simple:
      format: '[%(asctime)s][%(name)s line %(lineno)s][%(levelname)s] - %(message)s'
    colorlog:
      format: '[%(cyan)s%(asctime)s%(reset)s][%(blue)s%(name)s%(reset)s %(light_blue)s line %(lineno)s%(reset)s][%(log_color)s%(levelname)s%(reset)s]
          - %(message)s'

  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/${task_name}.log
