name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Create necessary directories
        mkdir -p data logs

        # Set environment variables
        export PYTHONPATH=$PWD
        export PROJECT_ROOT=$PWD

        python -m unittest discover -s src/tests

    - name: Clean up
      run: |
        rm -rf ~/.cache/pip
#  verify-functionality:
#    runs-on: ubuntu-latest
#    needs: test
#
#    steps:
#    - uses: actions/checkout@v3
#
#    - name: Set up Python
#      uses: actions/setup-python@v4
#      with:
#        python-version: '3.10'
#
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#
#    - name: Verify basic training functionality
#      run: |
#        # Create necessary directories
#        mkdir -p data logs
#
#        # Set environment variables
#        export PYTHONPATH=$PWD
#        export PROJECT_ROOT=$PWD
#
#        # Create a minimal training run to verify functionality
#        python src/main.py --mode "train" --config_path "configs"
